import { Prisma, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const main = async () => {
    const newMovies = await prisma.movies.createMany({
        data: [
            {
              title: '10 Cloverfield Lane',
              releaseYear: 2016,
              director: 1,
              genre: 1,
              rtScore: 90,
              sortTitle: '10 Cloverfield Lane',
              movieId: 'tt1179933',
              addedDate: new Date('2019-10-05'),
            },
            {
              title: '101 Dalmations',
              releaseYear: 1961,
              director: 2,
              genre: 2,
              rtScore: 98,
              sortTitle: '101 Dalmations',
              movieId: 'tt0055254',
              addedDate: new Date('2020-09-02'),
            },
            {
              title: '12 Monkeys',
              releaseYear: 1995,
              director: 3,
              genre: 3,
              rtScore: 89,
              sortTitle: '12 Monkeys',
              movieId: 'tt0114746',
              addedDate: new Date('2021-03-19'),
            },
            {
              title: '2 Fast 2 Furious',
              releaseYear: 2003,
              director: 4,
              genre: 4,
              collection: 1,
              rtScore: 36,
              sortTitle: '2 Fast 2 Furious',
              movieId: 'tt0322259',
              addedDate: new Date('2020-08-28'),
            },
            {
              title: '28 Days Later',
              releaseYear: 2002,
              director: 5,
              genre: 5,
              rtScore: 86,
              sortTitle: '28 Days Later',
              movieId: 'tt0289043',
              addedDate: new Date('2020-08-18'),
            },
            {
              title: '300',
              releaseYear: 2007,
              director: 6,
              genre: 4,
              rtScore: 60,
              sortTitle: '300',
              movieId: 'tt0416449',
              addedDate: new Date('2020-08-18'),
            },
            {
              title: '300: Rise of an Empire',
              releaseYear: 2014,
              director: 7,
              genre: 4,
              rtScore: 44,
              sortTitle: '300: Rise of an Empire',
              movieId: 'tt1253863',
              addedDate: new Date('2020-08-18'),
            },
            {
              title: 'Ad Astra',
              releaseYear: 2019,
              director: 8,
              genre: 3,
              rtScore: 83,
              sortTitle: 'Ad Astra',
              movieId: 'tt2935510',
              addedDate: new Date('2021-03-19'),
            },
            {
              title: 'The Adventures of Priscilla, Queen of the Desert',
              releaseYear: 1994,
              director: 9,
              genre: 6,
              rtScore: 96,
              sortTitle: 'Adventures of Priscilla, Queen of the Desert',
              movieId: 'tt0109045',
              addedDate: new Date('2021-04-06'),
            },
            {
              title: 'Airplane',
              releaseYear: 1980,
              director: 10,
              genre: 6,
              rtScore: 97,
              sortTitle: 'Airplane',
              movieId: 'tt0080339',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Akira',
              releaseYear: 1988,
              director: 11,
              genre: 7,
              rtScore: 90,
              sortTitle: 'Akira',
              movieId: 'tt0094625',
              addedDate: new Date('2020-09-13'),
            },
            {
              title: 'Aladdin',
              releaseYear: 1992,
              director: 12,
              genre: 2,
              rtScore: 94,
              sortTitle: 'Aladdin',
              movieId: 'tt0103639',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Alice in Wonderland',
              releaseYear: 1951,
              director: 13,
              genre: 2,
              rtScore: 81,
              sortTitle: 'Alice in Wonderland',
              movieId: 'tt0043274',
              addedDate: new Date('2020-11-18'),
            },
            {
              title: 'Alice in Wonderland',
              releaseYear: 2010,
              director: 14,
              genre: 2,
              rtScore: 51,
              sortTitle: 'Alice in Wonderland',
              movieId: 'tt1014759',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Alien',
              releaseYear: 1979,
              director: 15,
              genre: 5,
              collection: 2,
              rtScore: 97,
              sortTitle: 'Alien',
              movieId: 'tt0078748',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Alien 3',
              releaseYear: 1992,
              director: 16,
              genre: 5,
              collection: 2,
              rtScore: 42,
              sortTitle: 'Alien 3',
              movieId: 'tt0103644',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Alien Resurrection',
              releaseYear: 1997,
              director: 17,
              genre: 5,
              collection: 2,
              rtScore: 56,
              sortTitle: 'Alien Resurrection',
              movieId: 'tt0118583',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Alien vs Predator',
              releaseYear: 2004,
              director: 18,
              genre: 5,
          
              rtScore: 21,
              sortTitle: 'Alien vs Predator',
              movieId: 'tt0370263',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Alien vs Predator: Requiem',
              releaseYear: 2007,
              director: 19,
              genre: 5,
          
              rtScore: 11,
              sortTitle: 'Alien vs Predator: Requiem',
              movieId: 'tt0758730',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Alien: Covenant',
              releaseYear: 2017,
              director: 15,
              genre: 3,
              collection: 2,
              rtScore: 66,
              sortTitle: 'Alien: Covenant',
              movieId: 'tt2316204',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Aliens',
              releaseYear: 1986,
              director: 20,
              genre: 5,
              collection: 2,
              rtScore: 99,
              sortTitle: 'Aliens',
              movieId: 'tt0090605',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Anchorman',
              releaseYear: 2004,
              director: 21,
              genre: 6,
          
              rtScore: 66,
              sortTitle: 'Anchorman',
              movieId: 'tt0357413',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'And Now For Something Completely Different',
              releaseYear: 1971,
              director: 22,
              genre: 6,
              collection: 3,
              rtScore: 90,
              sortTitle: 'And Now For Something Completely Different',
              movieId: 'tt0066765',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Angels & Demons',
              releaseYear: 2009,
              director: 23,
              genre: 1,
          
              rtScore: 37,
              sortTitle: 'Angels & Demons',
              movieId: 'tt0808151',
              addedDate: new Date('2021-01-05'),
            },
            {
              title: 'Anna and the Apocalypse',
              releaseYear: 2017,
              director: 24,
              genre: 8,
          
              rtScore: 78,
              sortTitle: 'Anna and the Apocalypse',
              movieId: 'tt6433880',
              addedDate: new Date('2020-08-24'),
            },
            {
              title: 'Annabelle',
              releaseYear: 2014,
              director: 25,
              genre: 5,
          
              rtScore: 28,
              sortTitle: 'Annabelle',
              movieId: 'tt3322940',
              addedDate: new Date('2021-06-27'),
            },
            {
              title: 'Annabelle Comes Home',
              releaseYear: 2019,
              director: 26,
              genre: 5,
          
              rtScore: 64,
              sortTitle: 'Annabelle Comes Home',
              movieId: 'tt8350360',
              addedDate: new Date('2021-06-27'),
            },
            {
              title: 'Annabelle: Creation',
              releaseYear: 2017,
              director: 27,
              genre: 5,
          
              rtScore: 70,
              sortTitle: 'Annabelle: Creation',
              movieId: 'tt5140878',
              addedDate: new Date('2021-06-27'),
            },
            {
              title: 'Annie Get Your Gun',
              releaseYear: 1950,
              director: 28,
              genre: 8,
          
              rtScore: 100,
              sortTitle: 'Annie Get Your Gun',
              movieId: 'tt0042200',
              addedDate: new Date('2020-12-10'),
            },
            {
              title: 'Aquaman',
              releaseYear: 2018,
              director: 29,
              genre: 9,
          
              rtScore: 65,
              sortTitle: 'Aquaman',
              movieId: 'tt1477834',
              addedDate: new Date('2020-04-13'),
            },
            {
              title: 'Arsenic and Old Lace',
              releaseYear: 1944,
              director: 30,
              genre: 6,
          
              rtScore: 88,
              sortTitle: 'Arsenic and Old Lace',
              movieId: 'tt0036613',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: "At World's End",
              releaseYear: 2007,
              director: 31,
              genre: 10,
              collection: 4,
              rtScore: 44,
              sortTitle: "At World's End",
              movieId: 'tt0449088',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Atlantis: the Lost Empire',
              releaseYear: 2001,
              director: 32,
              genre: 2,
          
              rtScore: 49,
              sortTitle: 'Atlantis: the Lost Empire',
              movieId: 'tt0230011',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Atomic Blonde',
              releaseYear: 2017,
              director: 33,
              genre: 4,
          
              rtScore: 78,
              sortTitle: 'Atomic Blonde',
              movieId: 'tt2406566',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Attack of the Clones',
              releaseYear: 2002,
              director: 34,
              genre: 3,
              collection: 5,
              rtScore: 65,
              sortTitle: 'Attack of the Clones',
              movieId: 'tt0121765',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Audition',
              releaseYear: 2000,
              director: 35,
              genre: 5,
          
              rtScore: 81,
              sortTitle: 'Audition',
              movieId: 'tt0235198',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Avatar',
              releaseYear: 2009,
              director: 20,
              genre: 3,
          
              rtScore: 82,
              sortTitle: 'Avatar',
              movieId: 'tt0499549',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Avengers: Age of Ultron',
              releaseYear: 2015,
              director: 36,
              genre: 9,
              collection: 6,
              rtScore: 76,
              sortTitle: 'Avengers: Age of Ultron',
              movieId: 'tt2395427',
              addedDate: new Date('2020-11-26'),
            },
            {
              title: 'Avengers: Endgame',
              releaseYear: 2019,
              director: 37,
              genre: 9,
              collection: 6,
              rtScore: 94,
              sortTitle: 'Avengers: Endgame',
              movieId: 'tt4154796',
              addedDate: new Date('2020-11-26'),
            },
            {
              title: 'Avengers: Infinity War',
              releaseYear: 2018,
              director: 37,
              genre: 9,
              collection: 6,
              rtScore: 85,
              sortTitle: 'Avengers: Infinity War',
              movieId: 'tt4154756',
              addedDate: new Date('2020-11-18'),
            },
            {
              title: 'The Babadook',
              releaseYear: 2014,
              director: 38,
              genre: 5,
          
              rtScore: 98,
              sortTitle: 'Babadook',
              movieId: 'tt2321549',
              addedDate: new Date('2020-08-18'),
            },
            {
              title: 'Babe',
              releaseYear: 1995,
              director: 39,
              genre: 2,
          
              rtScore: 97,
              sortTitle: 'Babe',
              movieId: 'tt0112431',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Back to the Future',
              releaseYear: 1985,
              director: 40,
              genre: 3,
          
              rtScore: 96,
              sortTitle: 'Back to the Future',
              movieId: 'tt0088763',
              addedDate: new Date('2020-09-01'),
            },
            {
              title: 'Back to the Future Part 2',
              releaseYear: 1989,
              director: 40,
              genre: 3,
          
              rtScore: 65,
              sortTitle: 'Back to the Future Part 2',
              movieId: 'tt0096874',
              addedDate: new Date('2020-09-01'),
            },
            {
              title: 'Batman',
              releaseYear: 1989,
              director: 14,
              genre: 9,
              collection: 7,
              rtScore: 71,
              sortTitle: 'Batman',
              movieId: 'tt0096895',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Batman (1966)',
              releaseYear: 1966,
              director: 41,
              genre: 9,
              collection: 7,
              rtScore: 78,
              sortTitle: 'Batman (1966)',
              movieId: 'tt0059968',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Batman Begins',
              releaseYear: 2005,
              director: 42,
              genre: 9,
              collection: 7,
              rtScore: 84,
              sortTitle: 'Batman Begins',
              movieId: 'tt0372784',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Batman Returns',
              releaseYear: 1992,
              director: 14,
              genre: 9,
              collection: 7,
              rtScore: 78,
              sortTitle: 'Batman Returns',
              movieId: 'tt0103776',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Battle Royale',
              releaseYear: 2000,
              director: 43,
              genre: 3,
          
              rtScore: 88,
              sortTitle: 'Battle Royale',
              movieId: 'tt0266308',
              addedDate: new Date('2021-07-09'),
            },
            {
              title: 'Beasts of the Southern Wild',
              releaseYear: 2012,
              director: 44,
              genre: 15,
          
              rtScore: 87,
              sortTitle: 'Beasts of the Southern Wild',
              movieId: 'tt2125435',
              addedDate: new Date('2019-07-30'),
            },
            {
              title: 'A Beautiful Day in the Neighborhood',
              releaseYear: 2019,
              director: 45,
              genre: 11,
          
              rtScore: 95,
              sortTitle: 'Beautiful Day in the Neighborhood',
              movieId: 'tt3224458',
              addedDate: new Date('2021-04-07'),
            },
            {
              title: 'Beauty and the Beast',
              releaseYear: 1991,
              director: 32,
              genre: 2,
          
              rtScore: 94,
              sortTitle: 'Beauty and the Beast',
              movieId: 'tt0101414',
              addedDate: new Date('2021-08-30'),
            },
            {
              title: 'Bee Movie',
              releaseYear: 2007,
              director: 46,
              genre: 2,
          
              rtScore: 50,
              sortTitle: 'Bee Movie',
              movieId: 'tt0389790',
              addedDate: new Date('2020-09-07'),
            },
            {
              title: 'Beetlejuice',
              releaseYear: 1988,
              director: 14,
              genre: 6,
          
              rtScore: 84,
              sortTitle: 'Beetlejuice',
              movieId: 'tt0094721',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Best in Show',
              releaseYear: 2000,
              director: 47,
              genre: 6,
          
              rtScore: 94,
              sortTitle: 'Best in Show',
              movieId: 'tt0218839',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Big',
              releaseYear: 1988,
              director: 48,
              genre: 10,
          
              rtScore: 97,
              sortTitle: 'Big',
              movieId: 'tt0094737',
              addedDate: new Date('2021-01-19'),
            },
            {
              title: 'Big Fish',
              releaseYear: 2003,
              director: 14,
              genre: 15,
          
              rtScore: 75,
              sortTitle: 'Big Fish',
              movieId: 'tt0319061',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Big Hero 6',
              releaseYear: 2014,
              director: 49,
              genre: 2,
          
              rtScore: 89,
              sortTitle: 'Big Hero 6',
              movieId: 'tt2245084',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'The Big Lebowski',
              releaseYear: 1998,
              director: 50,
              genre: 6,
          
              rtScore: 83,
              sortTitle: 'Big Lebowski',
              movieId: 'tt0118715',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'The Birdcage',
              releaseYear: 1996,
              director: 51,
              genre: 6,
          
              rtScore: 79,
              sortTitle: 'Birdcage',
              movieId: 'tt0115685',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Black Bear',
              releaseYear: 2020,
              director: 52,
              genre: 15,
          
              rtScore: 88,
              sortTitle: 'Black Bear',
              movieId: 'tt9601220',
              addedDate: new Date('2020-12-13'),
            },
            {
              title: 'Black Panther',
              releaseYear: 2018,
              director: 53,
              genre: 9,
              collection: 6,
              rtScore: 97,
              sortTitle: 'Black Panther',
              movieId: 'tt1825683',
              addedDate: new Date('2019-11-02'),
            },
            {
              title: 'Black Sheep',
              releaseYear: 2006,
              director: 54,
              genre: 5,
          
              rtScore: 71,
              sortTitle: 'Black Sheep',
              movieId: 'tt0779982',
              addedDate: new Date('2020-02-16'),
            },
            {
              title: 'Black Swan',
              releaseYear: 2010,
              director: 55,
              genre: 1,
          
              rtScore: 85,
              sortTitle: 'Black Swan',
              movieId: 'tt0947798',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Black Widow',
              releaseYear: 2021,
              director: 56,
              genre: 9,
              collection: 6,
              rtScore: 79,
              sortTitle: 'Black Widow',
              movieId: 'tt3480822',
              addedDate: new Date('2021-10-14'),
            },
            {
              title: 'BlacKkKlansman',
              releaseYear: 2018,
              director: 57,
              genre: 15,
          
              rtScore: 96,
              sortTitle: 'BlacKkKlansman',
              movieId: 'tt7349662',
              addedDate: new Date('2020-08-28'),
            },
            {
              title: 'Blade Runner',
              releaseYear: 1982,
              director: 15,
              genre: 3,
          
              rtScore: 90,
              sortTitle: 'Blade Runner',
              movieId: 'tt0083658',
              addedDate: new Date('2021-06-26'),
            },
            {
              title: 'Blade Runner: 2049',
              releaseYear: 2017,
              director: 58,
              genre: 3,
          
              rtScore: 87,
              sortTitle: 'Blade Runner: 2049',
              movieId: 'tt1856101',
              addedDate: new Date('2020-05-23'),
            },
            {
              title: 'Blindness',
              releaseYear: 2008,
              director: 59,
              genre: 15,
          
              rtScore: 44,
              sortTitle: 'Blindness',
              movieId: 'tt0861689',
              addedDate: new Date('2020-03-23'),
            },
            {
              title: 'Bohemian Rhapsody',
              releaseYear: 2018,
              director: 60,
              genre: 11,
          
              rtScore: 61,
              sortTitle: 'Bohemian Rhapsody',
              movieId: 'tt1727824',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'Bombshell',
              releaseYear: 2019,
              director: 61,
              genre: 11,
          
              rtScore: 68,
              sortTitle: 'Bombshell',
              movieId: 'tt6394270',
              addedDate: new Date('2021-06-29'),
            },
            {
              title: 'The Book of Eli',
              releaseYear: 2010,
              director: 62,
              genre: 3,
              rtScore: 47,
              sortTitle: 'Book of Eli',
              movieId: 'tt1037705',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'The Book of Life',
              releaseYear: 2014,
              director: 63,
              genre: 2,
              rtScore: 82,
              sortTitle: 'Book of Life',
              movieId: 'tt2262227',
              addedDate: new Date('2020-11-09'),
            },
            {
              title: 'Booksmart',
              releaseYear: 2019,
              director: 64,
              genre: 6,
              rtScore: 97,
              sortTitle: 'Booksmart',
              movieId: 'tt1489887',
              addedDate: new Date('2020-05-12'),
            },
            {
              title: 'The Bourne Identity',
              releaseYear: 2002,
              director: 65,
              genre: 4,
              collection: 8,
              rtScore: 83,
              sortTitle: 'Bourne Identity',
              movieId: 'tt0258463',
              addedDate: new Date('2020-08-30'),
            },
            {
              title: 'The Bourne Legacy',
              releaseYear: 2012,
              director: 66,
              genre: 4,
              collection: 8,
              rtScore: 55,
              sortTitle: 'Bourne Legacy',
              movieId: 'tt1194173',
              addedDate: new Date('2020-08-31'),
            },
            {
              title: 'The Bourne Supremacy',
              releaseYear: 2004,
              director: 67,
              genre: 4,
              collection: 8,
              rtScore: 82,
              sortTitle: 'Bourne Supremacy',
              movieId: 'tt0372183',
              addedDate: new Date('2020-08-30'),
            },
            {
              title: 'The Bourne Ultimatum',
              releaseYear: 2007,
              director: 67,
              genre: 4,
              collection: 8,
              rtScore: 92,
              sortTitle: 'Bourne Ultimatum',
              movieId: 'tt0440963',
              addedDate: new Date('2020-08-30'),
            },
            {
              title: 'The Boxtrolls',
              releaseYear: 2014,
              director: 68,
              genre: 2,
              rtScore: 76,
              sortTitle: 'Boxtrolls',
              movieId: 'tt0787474',
              addedDate: new Date('2019-07-24'),
            },
            {
              title: 'The Boy',
              releaseYear: 2016,
              director: 69,
              genre: 5,
              rtScore: 30,
              sortTitle: 'Boy',
              movieId: 'tt3882082',
              addedDate: new Date('2020-09-01'),
            },
            {
              title: 'Boy Erased',
              releaseYear: 2018,
              director: 70,
              genre: 15,
              rtScore: 80,
              sortTitle: 'Boy Erased',
              movieId: 'tt7008872',
              addedDate: new Date('2021-06-2'),
            },
            {
              title: 'Brave',
              releaseYear: 2012,
              director: 71,
              genre: 2,
              collection: 9,
              rtScore: 78,
              sortTitle: 'Brave',
              movieId: 'tt1217209',
              addedDate: new Date('2020-05-12'),
            },
            {
              title: 'The Brave Little Toaster',
              releaseYear: 1987,
              director: 72,
              genre: 2,
              rtScore: 77,
              sortTitle: 'Brave Little Toaster',
              movieId: 'tt0092695',
              addedDate: new Date('2020-12-10'),
            },
            {
              title: 'Brazil',
              releaseYear: 1985,
              director: 3,
              genre: 3,
              rtScore: 98,
              sortTitle: 'Brazil',
              movieId: 'tt0088846',
              addedDate: new Date('2020-12-05'),
            },
            {
              title: 'Bridesmaids',
              releaseYear: 2011,
              director: 73,
              genre: 6,
              rtScore: 90,
              sortTitle: 'Bridesmaids',
              movieId: 'tt1478338',
              addedDate: new Date('2020-02-16'),
            },
            {
              title: 'The Bridges of Madison County',
              releaseYear: 1995,
              director: 74,
              genre: 15,
              rtScore: 90,
              sortTitle: 'Bridges of Madison County',
              movieId: 'tt0112579',
              addedDate: new Date('2021-06-25'),
            },
            {
              title: 'Brightburn',
              releaseYear: 2019,
              director: 75,
              genre: 3,
              rtScore: 57,
              sortTitle: 'Brightburn',
              movieId: 'tt7752126',
              addedDate: new Date('2021-10-31'),
            },
            {
              title: 'Bruce Almighty',
              releaseYear: 2003,
              director: 76,
              genre: 6,
              rtScore: 48,
              sortTitle: 'Bruce Almighty',
              movieId: 'tt0315327',
              addedDate: new Date('2020-02-10'),
            },
            {
              title: "A Bug's Life",
              releaseYear: 1998,
              director: 77,
              genre: 2,
              collection: 9,
              rtScore: 92,
              sortTitle: "Bug's Life",
              movieId: 'tt0120623',
              addedDate: new Date('2019-07-24'),
            },
          ]
    });

    if(newMovies) {
        console.log('! new Movies !')
    }
};

main().then(async () => {
  await prisma.$disconnect;
});

export {};
