import { Prisma, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const main = async () => {

    const movies = [
      {
        title: 'Caddyshack',
        releaseYear: 1980,
        director: 79,
        genre: 6,
        
        rtScore: 73,
        sortTitle: 'Caddyshack',
        movieId: 11977,
        addedDate: new Date('2021-04-20'),
      },
      {
        title: 'Captain America: Civil War',
        releaseYear: 2016,
        director: 37,
        genre: 9,
        collection: 6,
        rtScore: 90,
        sortTitle: 'Captain America: Civil War',
        movieId: 271110,
        addedDate: new Date('2021-07-08'),
      },
      {
        title: 'Captain America: the First Avenger',
        releaseYear: 2011,
        director: 80,
        genre: 9,
        collection: 6,
        rtScore: 79,
        sortTitle: 'Captain America: the First Avenger',
        movieId: 1771,
        addedDate: new Date('2021-07-08'),
      },
      {
        title: 'Captain America: the Winter Soldier',
        releaseYear: 2014,
        director: 37,
        genre: 9,
        collection: 6,
        rtScore: 90,
        sortTitle: 'Captain America: the Winter Soldier',
        movieId: 100402,
        addedDate: new Date('2021-07-08'),
      },
      {
        title: 'Captain Marvel',
        releaseYear: 2019,
        director: 81,
        genre: 9,
        collection: 6,
        rtScore: 78,
        sortTitle: 'Captain Marvel',
        movieId: 299537,
        addedDate: new Date('2020-02-08'),
      },
      {
        title: 'Carrie',
        releaseYear: 1976,
        director: 82,
        genre: 5,
        
        rtScore: 93,
        sortTitle: 'Carrie',
        movieId: 7340,
        addedDate: new Date('2021-10-17'),
      },
      {
        title: 'Casino Royale',
        releaseYear: 2006,
        director: 83,
        genre: 4,
        collection: 10,
        rtScore: 94,
        sortTitle: 'Casino Royale',
        movieId: 36557,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Casper',
        releaseYear: 1995,
        director: 84,
        genre: 2,
        
        rtScore: 50,
        sortTitle: 'Casper',
        movieId: 8839,
        addedDate: new Date('2020-09-22'),
      },
      {
        title: 'Catch Me If you Can',
        releaseYear: 2002,
        director: 85,
        genre: 11,
        
        rtScore: 96,
        sortTitle: 'Catch Me If you Can',
        movieId: 640,
        addedDate: new Date('2020-02-16'),
      },
      {
        title: 'Chappie',
        releaseYear: 2015,
        director: 86,
        genre: 3,
        
        rtScore: 33,
        sortTitle: 'Chappie',
        movieId: 198184,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Charlie and the Chocolate Factory',
        releaseYear: 2005,
        director: 14,
        genre: 2,
        
        rtScore: 83,
        sortTitle: 'Charlie and the Chocolate Factory',
        movieId: 118,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Chicken Run',
        releaseYear: 2000,
        director: 87,
        genre: 2,
        
        rtScore: 97,
        sortTitle: 'Chicken Run',
        movieId: 7443,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Christmas Vacation',
        releaseYear: 1989,
        director: 88,
        genre: 6,
        
        rtScore: 66,
        sortTitle: 'Christmas Vacation',
        movieId: 5825,
        addedDate: new Date('2020-02-18'),
      },
      {
        title: 'Clash of the Titans',
        releaseYear: 2010,
        director: 90,
        genre: 10,
        
        rtScore: 27,
        sortTitle: 'Clash of the Titans',
        movieId: 18823,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Close Encounters of the Third Kind',
        releaseYear: 1977,
        director: 85,
        genre: 3,
        
        rtScore: 94,
        sortTitle: 'Close Encounters of the Third Kind',
        movieId: 840,
        addedDate: new Date('2021-04-06'),
      },
      {
        title: 'Closet Monster',
        releaseYear: 2016,
        director: 91,
        genre: 15,
        
        rtScore: 80,
        sortTitle: 'Closet Monster',
        movieId: 353728,
        addedDate: new Date('2020-04-13'),
      },
      {
        title: 'Cloud Atlas',
        releaseYear: 2012,
        director: 92,
        genre: 3,
        
        rtScore: 66,
        sortTitle: 'Cloud Atlas',
        movieId: 83542,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Clue',
        releaseYear: 1985,
        director: 93,
        genre: 6,
        
        rtScore: 59,
        sortTitle: 'Clue',
        movieId: 15196,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'CODA',
        releaseYear: 2021,
        director: 94,
        genre: 15,
        
        rtScore: 94,
        sortTitle: 'CODA',
        movieId: 776503,
        addedDate: new Date('2022-03-29'),
      },
      {
        title: 'Con Air',
        releaseYear: 1997,
        director: 95,
        genre: 4,
        
        rtScore: 56,
        sortTitle: 'Con Air',
        movieId: 1701,
        addedDate: new Date('2021-01-05'),
      },
      {
        title: 'Coneheads',
        releaseYear: 1993,
        director: 96,
        genre: 6,
        
        rtScore: 35,
        sortTitle: 'Coneheads',
        movieId: 9612,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Contact',
        releaseYear: 1997,
        director: 40,
        genre: 3,
        
        rtScore: 66,
        sortTitle: 'Contact',
        movieId: 686,
        addedDate: new Date('2021-01-19'),
      },
      {
        title: 'Contagion',
        releaseYear: 2011,
        director: 97,
        genre: 15,
        
        rtScore: 84,
        sortTitle: 'Contagion',
        movieId: 39538,
        addedDate: new Date('2020-03-23'),
      },
      {
        title: 'Coraline',
        releaseYear: 2009,
        director: 98,
        genre: 2,
        
        rtScore: 90,
        sortTitle: 'Coraline',
        movieId: 14836,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Crazy Rich Asians',
        releaseYear: 2018,
        director: 100,
        genre: 6,
        
        rtScore: 91,
        sortTitle: 'Crazy Rich Asians',
        movieId: 455207,
        addedDate: new Date('2020-05-20'),
      },
      {
        title: 'Cruel Intentions',
        releaseYear: 1999,
        director: 101,
        genre: 15,
        
        rtScore: 55,
        sortTitle: 'Cruel Intentions',
        movieId: 796,
        addedDate: new Date('2021-04-18'),
      },
      {
        title: 'Cruella',
        releaseYear: 2021,
        director: 102,
        genre: 6,
        
        rtScore: 74,
        sortTitle: 'Cruella',
        movieId: 337404,
        addedDate: new Date('2021-06-02'),
      },
      {
        title: 'The Curse of the Black Pearl',
        releaseYear: 2003,
        director: 31,
        genre: 10,
        collection: 4,
        rtScore: 79,
        sortTitle: 'Curse of the Black Pearl',
        movieId: 22,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Dancer in the Dark',
        releaseYear: 2000,
        director: 104,
        genre: 15,
        
        rtScore: 68,
        sortTitle: 'Dancer in the Dark',
        movieId: 16,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Darkest Hour',
        releaseYear: 2017,
        director: 105,
        genre: 11,
        
        rtScore: 84,
        sortTitle: 'Darkest Hour',
        movieId: 399404,
        addedDate: new Date('2021-06-29'),
      },
      {
        title: 'Dawn of the Planet of the Apes',
        releaseYear: 2014,
        director: 106,
        genre: 4,
        collection: 12,
        rtScore: 91,
        sortTitle: 'Dawn of the Planet of the Apes',
        movieId: 119450,
        addedDate: new Date('2019-12-29'),
      },
      {
        title: "Dead Man's Chest",
        releaseYear: 2006,
        director: 31,
        genre: 10,
        collection: 4,
        rtScore: 53,
        sortTitle: "Dead Man's Chest",
        movieId: 58,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Deadpool',
        releaseYear: 2016,
        director: 107,
        genre: 9,
        collection: 13,
        rtScore: 84,
        sortTitle: 'Deadpool',
        movieId: 293660,
        addedDate: new Date('2019-07-26'),
      },
      {
        title: 'Deadpool 2',
        releaseYear: 2018,
        director: 33,
        genre: 9,
        collection: 13,
        rtScore: 83,
        sortTitle: 'Deadpool 2',
        movieId: 383498,
        addedDate: new Date('2019-07-27'),
      },
      {
        title: 'Deep Blue Sea',
        releaseYear: 1999,
        director: 99,
        genre: 4,
        
        rtScore: 60,
        sortTitle: 'Deep Blue Sea',
        movieId: 8914,
        addedDate: new Date('2019-08-04'),
      },
      {
        title: 'Despicable Me',
        releaseYear: 2010,
        director: 111,
        genre: 2,
        
        rtScore: 81,
        sortTitle: 'Despicable Me',
        movieId: 20352,
        addedDate: new Date('2019-09-16'),
      },
      {
        title: 'Despicable Me 2',
        releaseYear: 2013,
        director: 111,
        genre: 2,
        
        rtScore: 75,
        sortTitle: 'Despicable Me 2',
        movieId: 93456,
        addedDate: new Date('2020-09-04'),
      },
      {
        title: 'Diamonds are Forever',
        releaseYear: 1971,
        director: 114,
        genre: 4,
        collection: 10,
        rtScore: 64,
        sortTitle: 'Diamonds are Forever',
        movieId: 681,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Die Another Day',
        releaseYear: 2002,
        director: 115,
        genre: 4,
        collection: 10,
        rtScore: 57,
        sortTitle: 'Die Another Day',
        movieId: 36669,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Die Hard',
        releaseYear: 1988,
        director: 116,
        genre: 4,
        
        rtScore: 94,
        sortTitle: 'Die Hard',
        movieId: 562,
        addedDate: new Date('2022-10-03'),
      },
      {
        title: 'Die Hard 2',
        releaseYear: 1990,
        director: 99,
        genre: 4,
        
        rtScore: 69,
        sortTitle: 'Die Hard 2',
        movieId: 1573,
        addedDate: new Date('2022-10-03'),
      },
      {
        title: 'District 9',
        releaseYear: 2009,
        director: 86,
        genre: 3,
        
        rtScore: 90,
        sortTitle: 'District 9',
        movieId: 17654,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Django Unchained',
        releaseYear: 2012,
        director: 117,
        genre: 15,
        
        rtScore: 86,
        sortTitle: 'Django Unchained',
        movieId: 68718,
        addedDate: new Date('2019-08-03'),
      },
      {
        title: 'Doctor Sleep',
        releaseYear: 2019,
        director: 118,
        genre: 5,
        
        rtScore: 78,
        sortTitle: 'Doctor Sleep',
        movieId: 501170,
        addedDate: new Date('2021-03-19'),
      },
      {
        title: 'Doctor Strange',
        releaseYear: 2016,
        director: 119,
        genre: 9,
        collection: 6,
        rtScore: 89,
        sortTitle: 'Doctor Strange',
        movieId: 284052,
        addedDate: new Date('2020-07-30'),
      },
      {
        title: 'Dogma',
        releaseYear: 1999,
        director: 120,
        genre: 6,
        
        rtScore: 67,
        sortTitle: 'Dogma',
        movieId: 1832,
        addedDate: new Date('2019-08-04'),
      },
      {
        title: 'Donnie Darko',
        releaseYear: 2001,
        director: 121,
        genre: 15,
        
        rtScore: 87,
        sortTitle: 'Donnie Darko',
        movieId: 141,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Downsizing',
        releaseYear: 2017,
        director: 122,
        genre: 3,
        
        rtScore: 47,
        sortTitle: 'Downsizing',
        movieId: 301337,
        addedDate: new Date('2021-06-09'),
      },
      {
        title: 'Dr. No',
        releaseYear: 1962,
        director: 123,
        genre: 4,
        collection: 10,
        rtScore: 96,
        sortTitle: 'Dr. No',
        movieId: 646,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Dragon Ball Super: Broly',
        releaseYear: 2018,
        director: 124,
        genre: 7,
        
        rtScore: 84,
        sortTitle: 'Dragon Ball Super: Broly',
        movieId: 503314,
        addedDate: new Date('2020-08-01'),
      },
      {
        title: 'Duck Soup',
        releaseYear: 1933,
        director: 125,
        genre: 6,
        
        rtScore: 92,
        sortTitle: 'Duck Soup',
        movieId: 3063,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Dune',
        releaseYear: 2021,
        director: 58,
        genre: 3,
        
        rtScore: 83,
        sortTitle: 'Dune',
        movieId: 438631,
        addedDate: new Date('2022-03-28'),
      },
      {
        title: 'Dunkirk',
        releaseYear: 2017,
        director: 42,
        genre: 12,
        
        rtScore: 93,
        sortTitle: 'Dunkirk',
        movieId: 374720,
        addedDate: new Date('2019-12-30'),
      },
      {
        title: 'Edward Scissorhands',
        releaseYear: 1990,
        director: 14,
        genre: 15,
        
        rtScore: 90,
        sortTitle: 'Edward Scissorhands',
        movieId: 162,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'A Fish Called Wanda',
        releaseYear: 1988,
        director: 155,
        genre: 6,
        
        rtScore: 95,
        sortTitle: 'Fish Called Wanda',
        movieId: 623,
        addedDate: new Date('2021-03-20'),
      },
      {
        title: 'Harry Potter and the Chamber of Secrets',
        releaseYear: 2002,
        director: 185,
        genre: 10,
        collection: 16,
        rtScore: 83,
        sortTitle: 'Harry Potter and the Chamber of Secrets',
        movieId: 672,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Harry Potter and the Deathly Hallows Part 1',
        releaseYear: 2010,
        director: 139,
        genre: 10,
        collection: 16,
        rtScore: 77,
        sortTitle: 'Harry Potter and the Deathly Hallows Part 1',
        movieId: 12444,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Harry Potter and the Deathly Hallows Part 2',
        releaseYear: 2011,
        director: 139,
        genre: 10,
        collection: 16,
        rtScore: 96,
        sortTitle: 'Harry Potter and the Deathly Hallows Part 2',
        movieId: 12445,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Harry Potter and the Goblet of Fire',
        releaseYear: 2005,
        director: 186,
        genre: 10,
        collection: 16,
        rtScore: 88,
        sortTitle: 'Harry Potter and the Goblet of Fire',
        movieId: 674,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Harry Potter and the Half-blood Prince',
        releaseYear: 2009,
        director: 139,
        genre: 10,
        collection: 16,
        rtScore: 83,
        sortTitle: 'Harry Potter and the Half-blood Prince',
        movieId: 767,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Harry Potter and the Order of the Phoenix',
        releaseYear: 2007,
        director: 139,
        genre: 10,
        collection: 16,
        rtScore: 78,
        sortTitle: 'Harry Potter and the Order of the Phoenix',
        movieId: 675,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Harry Potter and the Prisoner of Azkaban',
        releaseYear: 2004,
        director: 176,
        genre: 10,
        collection: 16,
        rtScore: 90,
        sortTitle: 'Harry Potter and the Prisoner of Azkaban',
        movieId: 673,
        addedDate: new Date('2019-07-28'),
      },
      {
        title: "Harry Potter and the Sorcerer's Stone",
        releaseYear: 2001,
        director: 185,
        genre: 10,
        collection: 16,
        rtScore: 81,
        sortTitle: "Harry Potter and the Sorcerer's Stone",
        movieId: 671,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'The Hobbit: An Unexpected Journey',
        releaseYear: 2012,
        director: 147,
        genre: 10,
        
        rtScore: 64,
        sortTitle: 'Hobbit: An Unexpected Journey',
        movieId: 49051,
        addedDate: new Date('2021-07-28'),
      },
      {
        title: 'The Hobbit: the Battle of the Five Armies',
        releaseYear: 2014,
        director: 147,
        genre: 10,
        
        rtScore: 59,
        sortTitle: 'Hobbit: the Battle of the Five Armies',
        movieId: 122917,
        addedDate: new Date('2021-07-29'),
      },
      {
        title: 'The Hobbit: the Desolation of Smaug',
        releaseYear: 2013,
        director: 147,
        genre: 10,
        
        rtScore: 74,
        sortTitle: 'Hobbit: the Desolation of Smaug',
        movieId: 57158,
        addedDate: new Date('2021-07-28'),
      },
      {
        title: 'The Hunger Games',
        releaseYear: 2012,
        director: 198,
        genre: 4,
        
        rtScore: 84,
        sortTitle: 'Hunger Games',
        movieId: 70160,
        addedDate: new Date('2021-01-19'),
      },
      {
        title: 'The Hunger Games: Catching Fire',
        releaseYear: 2013,
        director: 199,
        genre: 4,
        
        rtScore: 90,
        sortTitle: 'Hunger Games: Catching Fire',
        movieId: 101299,
        addedDate: new Date('2021-01-19'),
      },
      {
        title: 'The Hunger Games: Mockingjay Part 1',
        releaseYear: 2014,
        director: 199,
        genre: 4,
        
        rtScore: 68,
        sortTitle: 'Hunger Games: Mockingjay Part 1',
        movieId: 131631,
        addedDate: new Date('2021-01-19'),
      },
      {
        title: 'The Hunger Games: Mockingjay Part 2',
        releaseYear: 2015,
        director: 199,
        genre: 4,
        
        rtScore: 69,
        sortTitle: 'Hunger Games: Mockingjay Part 2',
        movieId: 131634,
        addedDate: new Date('2021-01-19'),
      },
      {
        title: 'A Nightmare on Elm Street',
        releaseYear: 1984,
        director: 274,
        genre: 5,
        
        rtScore: 95,
        sortTitle: 'Nightmare on Elm Street',
        movieId: 377,
        addedDate: new Date('2021-10-17'),
      },
      {
        title: 'On Stranger Tides',
        releaseYear: 2011,
        director: 210,
        genre: 10,
        collection: 4,
        rtScore: 33,
        sortTitle: 'On Stranger Tides',
        movieId: 1865,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'A Quiet Place',
        releaseYear: 2018,
        director: 298,
        genre: 5,
        
        rtScore: 95,
        sortTitle: 'Quiet Place',
        movieId: 447332,
        addedDate: new Date('2020-05-13'),
      },
      {
        title: 'Resident Evil',
        releaseYear: 2002,
        director: 18,
        genre: 4,
        collection: 26,
        rtScore: 35,
        sortTitle: 'Resident Evil',
        movieId: 1576,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Resident Evil: Afterlife',
        releaseYear: 2010,
        director: 18,
        genre: 4,
        collection: 26,
        rtScore: 23,
        sortTitle: 'Resident Evil: Afterlife',
        movieId: 35791,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Resident Evil: Apocalypse',
        releaseYear: 2004,
        director: 303,
        genre: 4,
        collection: 26,
        rtScore: 20,
        sortTitle: 'Resident Evil: Apocalypse',
        movieId: 1577,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Resident Evil: Extinction',
        releaseYear: 2007,
        director: 290,
        genre: 4,
        collection: 26,
        rtScore: 23,
        sortTitle: 'Resident Evil: Extinction',
        movieId: 7737,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Resident Evil: Retribution',
        releaseYear: 2012,
        director: 18,
        genre: 4,
        collection: 26,
        rtScore: 29,
        sortTitle: 'Resident Evil: Retribution',
        movieId: 71679,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Resident Evil: The Final Chapter',
        releaseYear: 2016,
        director: 18,
        genre: 4,
        collection: 26,
        rtScore: 38,
        sortTitle: 'Resident Evil: The Final Chapter',
        movieId: 173897,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Return of the Jedi',
        releaseYear: 1983,
        director: 34,
        genre: 3,
        collection: 5,
        rtScore: 82,
        sortTitle: 'Return of the Jedi',
        movieId: 1892,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'The Return of the King',
        releaseYear: 2003,
        director: 147,
        genre: 10,
        collection: 14,
        rtScore: 93,
        sortTitle: 'Return of the King',
        movieId: 122,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'Revenge of the Sith',
        releaseYear: 2005,
        director: 34,
        genre: 3,
        collection: 5,
        rtScore: 80,
        sortTitle: 'Revenge of the Sith',
        movieId: 1895,
        addedDate: new Date('2019-07-24'),
      },
      {
        title: 'A View to a Kill',
        releaseYear: 1985,
        director: 158,
        genre: 4,
        collection: 10,
        rtScore: 36,
        sortTitle: 'View to a Kill',
        movieId: 707,
        addedDate: new Date('2019-07-24'),
      },
    ];    

    
    const newMovies = await prisma.movies.createMany({
      data: movies,
    });

    if(newMovies) {
      console.log('New Movies Added!');
    }
};

main().then(async () => {
  await prisma.$disconnect;
});

export {};
